using System;
using System.Collections.Generic;

namespace ServiceMonitorEVK.Source.Constants
{
    internal class MonitorConstants
    {

        public static readonly Dictionary<string, string> ManufacturerDictionary =
            new(StringComparer.OrdinalIgnoreCase)
            {
                { "ACER", "Acer" },
                { "ACI", "Asus (ASUSTeK Computer Inc.)" },
                { "ACT", "Targa" },
                { "ADI", "ADI Corporation" },
                { "AMW", "AMW" },
                { "AOC", "AOC International (USA) Ltd." },
                { "API", "Acer America Corp." },
                { "APP", "Apple" },
                { "ART", "ArtMedia" },
                { "AST", "AST Research" },
                { "ASUS", "ASUS" },
                { "AUO", "AU Optronics" },
                { "BENQ", "BenQ" },
                { "BNQ", "BenQ Corporation" },
                { "BOE", "BOE Display Technology" },
                { "CASIO", "Casio" },
                { "CMN", "Chi Mei" },
                { "CPQ", "COMPAQ Computer Corp." },
                { "CPL", "Compal Electronics, Inc. / ALFA" },
                { "CTX", "CTX / Chuntex Electronic Co." },
                { "DEC", "Digital Equipment Corporation" },
                { "DELL", "Dell" },
                { "DPC", "Delta Electronics, Inc." },
                { "DWE", "Daewoo Telecom Ltd" },
                { "ECS", "ELITEGROUP Computer Systems" },
                { "EIZ", "EIZO Corporation" },
                { "EPI", "Envision Peripherals, Inc." },
                { "FCM", "Funai Electric Company of Taiwan" },
                { "FUS", "Fujitsu Siemens" },
                { "GIGABYTE", "Gigabyte" },
                { "GSM", "LG Electronics Inc. (GoldStar Technology, Inc.)" },
                { "GWY", "Gateway 2000" },
                { "HAIER", "Haier" },
                { "HANNSTAR", "HannStar" },
                { "HISENSE", "Hisense" },
                { "HEI", "Hyundai Electronics Industries Co., Ltd." },
                { "HIQ", "Hyundai ImageQuest" },
                { "HIT", "Hitachi" },
                { "HP", "Hewlett-Packard" },
                { "HSD", "Hannspree Inc." },
                { "HSL", "Hansol Electronics" },
                { "HTC", "Hitachi Ltd. / Nissei Sangyo America Ltd." },
                { "HUA", "Huawei" },
                { "HWP", "Hewlett Packard (HP)" },
                { "IBM", "IBM PC Company" },
                { "ICL", "Fujitsu ICL" },
                { "IFS", "InFocus" },
                { "INSIGNIA", "Insignia" },
                { "IQT", "Hyundai" },
                { "IVM", "Iiyama" },
                { "JVC", "JVC" },
                { "KDS", "KDS USA" },
                { "KFC", "KFC Computek" },
                { "KOIZUMI", "Koizumi" },
                { "KONKA", "Konka" },
                { "LEN", "Lenovo" },
                { "LG", "LG" },
                { "LGD", "LG Display" },
                { "LKM", "ADLAS / AZALEA" },
                { "LNK", "LINK Technologies, Inc." },
                { "LPL", "LG Philips" },
                { "LTN", "Lite-On" },
                { "MAG", "MAG InnoVision" },
                { "MAX", "Maxdata Computer GmbH" },
                { "MEI", "Panasonic Comm. & Systems Co." },
                { "MEL", "Mitsubishi Electronics" },
                { "MIC", "Microsoft" },
                { "MIR", "Miro Computer Products AG" },
                { "MITSUBISHI", "Mitsubishi Electric" },
                { "MSI", "MSI" },
                { "NAN", "NANAO" },
                { "NEC", "NEC Display Solutions" },
                { "NOK", "Nokia" },
                { "NVD", "Nvidia" },
                { "OQI", "OPTIQUEST" },
                { "PACKARD BELL", "Packard Bell" },
                { "PBN", "Packard Bell" },
                { "PCK", "Daewoo" },
                { "PDC", "Polaroid" },
                { "PHILIPS", "Philips" },
                { "PHL", "Philips Consumer Electronics Co." },
                { "PLANAR", "Planar Systems" },
                { "PGS", "Princeton Graphic Systems" },
                { "PROVIEW", "Proview" },
                { "PRT", "Princeton" },
                { "RAZER", "Razer" },
                { "REL", "Relisys" },
                { "SAMSUNG", "Samsung" },
                { "SANYO", "Sanyo" },
                { "SEC", "Seiko Epson Corporation" },
                { "SHARP", "Sharp" },
                { "SKYWORTH", "Skyworth" },
                { "SMC", "Samtron" },
                { "SMI", "Smile" },
                { "SNI", "Siemens Nixdorf" },
                { "SONY", "Sony" },
                { "SPT", "Sceptre" },
                { "SRC", "Shamrock Technology" },
                { "STN", "Samtron" },
                { "STP", "Sceptre" },
                { "TAT", "Tatung Co. of America, Inc." },
                { "TATUNG", "Tatung" },
                { "TCL", "TCL Technology" },
                { "THOMSON", "Thomson" },
                { "TSB", "Toshiba" },
                { "UNM", "Unisys Corporation" },
                { "VESTEL", "Vestel" },
                { "VIEW", "ViewSonic" },
                { "VIZIO", "Vizio" },
                { "VSC", "ViewSonic Corporation" },
                { "WTC", "Wen Technology" },
                { "ZCM", "Zenith Data Systems" },
                { "WESTINGHOUSE", "Westinghouse" }
            };
    }
}
