//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitorEVK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceMonitorEVK.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing bad pixels.
        /// </summary>
        internal static string buttonServiceFixPixel {
            get {
                return ResourceManager.GetString("buttonServiceFixPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing monitor.
        /// </summary>
        internal static string buttonTestingMonitor {
            get {
                return ResourceManager.GetString("buttonTestingMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically show info from serial number (only for one monitor).
        /// </summary>
        internal static string checkBoxAutoShow {
            get {
                return ResourceManager.GetString("checkBoxAutoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Information.
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full info.
        /// </summary>
        internal static string fullInfoPage {
            get {
                return ResourceManager.GetString("fullInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        internal static string labelAsClass {
            get {
                return ResourceManager.GetString("labelAsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaned?:.
        /// </summary>
        internal static string labelAsCleaned {
            get {
                return ResourceManager.GetString("labelAsCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string labelAsCountry {
            get {
                return ResourceManager.GetString("labelAsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal (H\W):.
        /// </summary>
        internal static string labelAsDIagHW {
            get {
                return ResourceManager.GetString("labelAsDIagHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal:.
        /// </summary>
        internal static string labelAsDiagonal {
            get {
                return ResourceManager.GetString("labelAsDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer:.
        /// </summary>
        internal static string labelAsManufact {
            get {
                return ResourceManager.GetString("labelAsManufact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        internal static string labelAsModel {
            get {
                return ResourceManager.GetString("labelAsModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month:.
        /// </summary>
        internal static string labelAsMonth {
            get {
                return ResourceManager.GetString("labelAsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictured?:.
        /// </summary>
        internal static string labelAsPicture {
            get {
                return ResourceManager.GetString("labelAsPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place:.
        /// </summary>
        internal static string labelAsPlace {
            get {
                return ResourceManager.GetString("labelAsPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code ID:.
        /// </summary>
        internal static string labelAsProductId {
            get {
                return ResourceManager.GetString("labelAsProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        internal static string labelAsResolution {
            get {
                return ResourceManager.GetString("labelAsResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.:.
        /// </summary>
        internal static string labelAsSerial {
            get {
                return ResourceManager.GetString("labelAsSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaner:.
        /// </summary>
        internal static string labelAssetCleaner1 {
            get {
                return ResourceManager.GetString("labelAssetCleaner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested?:.
        /// </summary>
        internal static string labelAsTested {
            get {
                return ResourceManager.GetString("labelAsTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester:.
        /// </summary>
        internal static string labelAsTester {
            get {
                return ResourceManager.GetString("labelAsTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string labelAsYear {
            get {
                return ResourceManager.GetString("labelAsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string labelCountry {
            get {
                return ResourceManager.GetString("labelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal (H\W):.
        /// </summary>
        internal static string labelDiagonal {
            get {
                return ResourceManager.GetString("labelDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency:.
        /// </summary>
        internal static string labelFrequency {
            get {
                return ResourceManager.GetString("labelFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer:.
        /// </summary>
        internal static string labelManufacturer {
            get {
                return ResourceManager.GetString("labelManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        internal static string LabelModel {
            get {
                return ResourceManager.GetString("LabelModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string labelMonitor {
            get {
                return ResourceManager.GetString("labelMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month:.
        /// </summary>
        internal static string labelMonth {
            get {
                return ResourceManager.GetString("labelMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPI:.
        /// </summary>
        internal static string labelPPI {
            get {
                return ResourceManager.GetString("labelPPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code ID:.
        /// </summary>
        internal static string labelProductCode {
            get {
                return ResourceManager.GetString("labelProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.:.
        /// </summary>
        internal static string labelSerial {
            get {
                return ResourceManager.GetString("labelSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number:.
        /// </summary>
        internal static string LabelSerialNo {
            get {
                return ResourceManager.GetString("LabelSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size monitor (cm.):.
        /// </summary>
        internal static string labelSize {
            get {
                return ResourceManager.GetString("labelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string labelYear {
            get {
                return ResourceManager.GetString("labelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable:.
        /// </summary>
        internal static string lableAsCable {
            get {
                return ResourceManager.GetString("lableAsCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change resolution.
        /// </summary>
        internal static string lableChanRes {
            get {
                return ResourceManager.GetString("lableChanRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        internal static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        internal static string resolutionPage {
            get {
                return ResourceManager.GetString("resolutionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search info.
        /// </summary>
        internal static string searchInfoPage {
            get {
                return ResourceManager.GetString("searchInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set. Max. Resolution.
        /// </summary>
        internal static string SetMaxResolution {
            get {
                return ResourceManager.GetString("SetMaxResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set. Resolution.
        /// </summary>
        internal static string SetResolution {
            get {
                return ResourceManager.GetString("SetResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        internal static string showInfoPage {
            get {
                return ResourceManager.GetString("showInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string tabPageMain {
            get {
                return ResourceManager.GetString("tabPageMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string testMonitorPage {
            get {
                return ResourceManager.GetString("testMonitorPage", resourceCulture);
            }
        }
    }
}
